"""Main FastAPI application."""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import os
from . import oauth, tenant, workflows, stripe, local_dev, auth

app = FastAPI(
    title="CORTA API",
    description="AI-powered project management SaaS Platform",
    version="1.0.0",
)

# Determine allowed origins for CORS
frontend_origin = os.getenv("FRONTEND_ORIGIN")
default_origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
if frontend_origin:
    default_origins.append(frontend_origin)
else:
    # Railway autogenerated domain (fallback to avoid manual config)
    railway_domain = os.getenv("RAILWAY_STATIC_URL")
    if railway_domain:
        default_origins.append(railway_domain)

app.add_middleware(
    CORSMiddleware,
    allow_origins=default_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include routers
app.include_router(auth.router)
app.include_router(oauth.router)
app.include_router(workflows.router)

# Stripe router (optional)
try:
    app.include_router(stripe.router)
except Exception:
    pass  # Stripe not available

# Local dev router (only in development)
if os.getenv("ENV") != "production":
    app.include_router(local_dev.router)


@app.get("/")
async def root():
    return {"message": "CORTA API", "version": "1.0.0"}


@app.get("/health")
async def health():
    return {"status": "healthy"}
